{{- if .Values.rbac.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scheduled-snapshot-operator.name" . }}
  labels:
    {{- include "scheduled-snapshot-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - k8s.ryanorth.io
    resources:
      - scheduledvolumesnapshots
    verbs:
      - '*'
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
      - volumesnapshotcontents
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - list
{{- end }}
