{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" -}}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "scheduled-snapshot-operator.name" . }}
  labels:
    {{- include "scheduled-snapshot-operator.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        {{- if .Values.podSecurityConext }}
        securityContext:
{{ toYaml .Values.podSecurityConext | indent 10 }}
        {{- end }}
        metadata:
          annotations:
{{ toYaml .Values.podAnnotations | indent 12 }}
        spec:
          serviceAccountName: {{ include "scheduled-snapshot-operator.name" . }}
          {{- if .Values.image.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
              {{- if .Values.containerSecurityContext }}
              securityContext:
{{ toYaml .Values.containerSecurityContext | indent 16 }}
              {{- end }}
              env:
                - name: LOG_LEVEL
                  value: "{{ .Values.logLevel }}"
          restartPolicy: Never
