{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduled-snapshot-operator.name" . }}
  labels:
{{ include "scheduled-snapshot-operator.labels" . | nindent 4 }}
{{- end }}
