{{ range .Values.snapshotClasses -}}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  {{- toYaml .metadata | nindent 2 }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
driver: {{ .driver }}
deletionPolicy: {{ .deletionPolicy | default "Delete" }}
{{ end -}}
